### ISSUE TITLE
[playground] Documenting object/class methods

### ISSUE THREAD

**Issue by Wenzil** [Microsoft/tsdoc#116]
I'm experimenting with the [TSDoc Playground](https://microsoft.github.io/tsdoc/#) and I can't seem to make it parse comments for methods defined within a class or object. Here's a sample:

```ts
/**
 * Some sample class
 */
export class MyClass {
    /**
     * Returns the average of two numbers.
     */
    getAverage(x, y) {
        return (x + y) / 2.0;
    }
}
```

The method documentation isn't part of the generated AST. Here is the AST output:

```
- Comment
  - Section
    - Paragraph
      - PlainText
        * PlainText="Some sample class"
      - SoftBreak
        * SoftBreak="\n"
```

**Comment by pgonzal** [comment]
The TSDoc playground invokes a library API that simply reads the first comment it sees and then stops when it reaches the `*/` delimiter.  This is a reasonable behavior for the API, since maybe you want the library to help you figure out where the comment ends, and then another parser rule will take over from there.

But I agree that this is highly confusing for the playground web site.  We should make it more clear.  See my notes for https://github.com/Microsoft/tsdoc/issues/115

**Comment by pgonzal** [comment]
This is really the same issue as #155.  Let's discuss it over there.
