### ISSUE TITLE
Consider a more human readable style like markdown or rst rather than just repeating JavaDoc

### ISSUE THREAD

**Issue by ems-ja** [Microsoft/tsdoc#144]
```
export class Statistics {
  /**
  Returns the average of two numbers.

  Remarks
  ------- 
  This method is part of the {@link core-library#Statistics | Statistics subsystem}.
   
  Parameters
  ---------- 
  x - The first input number
  y - The second input number
   
  Returns
  ----------- 
  The arithmetic mean of `x` and `y`
  
   */
  public static getAverage(x: number, y: number): number {
    return (x + y) / 2.0;
  }
}
```
An implementation of this would be [numpydoc]( https://numpydoc.readthedocs.io/en/latest/format.html#overview).

Nevermind.

**Comment by octogonz** [comment]
As mentioned in the charter, the main priorities of TSDoc are:
1. To fit naturally with today's large existing TypeScript code bases and the conventions they use.
2. To ensure that when the content ends up on a web site, it does not contain any mistakes (e.g. because different tools disagree about syntax)
3. In particular, allow tools to safely process content that contains unrecognized custom tags from some other tool

Numpydoc doesn't seem to meet these goals.  Markdown objectively works against these goals, because in trying to make the input more readable, it makes the output very unpredictable (due to grammar ambiguities).  Most of the TSDoc work was focused around limiting this effect, while preserving the essential character of Markdown.

**Comment by octogonz** [comment]
Closing this issue since I believe the original question was answered.  If not, please reopen.
