### ISSUE TITLE
Unescaped tag that contains special character produces tsdoc-text-after-tag error

### ISSUE THREAD

**Issue by skaapgif** [Microsoft/tsdoc#157]
The following TSDoc comment for a class:
```ts
/**
 * I refer to incorrectly escaped external package: @elastic/eui
 */
```

Produces the error:
> (tsdoc-text-after-tag) A TSDoc tag must be followed by whitespace

To solve this the '@' can be escaped like: 
```ts
/**
 * I refer to incorrectly escaped external package: \@elastic/eui
 */
```

Instead of throwing an error about whitespace, I would expect the parser to throw an invalid tag error since even with added whitespace this could not form a valid tag. Note: this seems to work as expected if the invalid tag doesn't contain special characters like the '/'.

**Comment by octogonz** [comment]
@skaapgif  It sounds like you're proposing that instead of this:

> A TSDoc tag must be followed by whitespace

....the error should instead say something like this:

> The tag "@elastic" is not a valid TSDoc tag

Is that right?  

Although the error message refers to a tag, the parser is actually explaining why the tag syntax is being rejected.  The AST token will end up as `PlainText`, not `BlockTag`.  This heuristic seems correct, since in your example "@elastic" was not intended to be a tag.  Thus, maybe it doesn't make sense to go further down the path of testing whether the tag name is defined or supported or not.

Instead, maybe the real problem our usage of the phrase `A TSDoc tag` when talking about "@elastic".  A novice person might wonder "What tag?  That text is obviously not a tag!"

Maybe we could change the error to something like this:

> The token "@elastic" looks like a TSDoc tag, but it contains an invalid character "/".

**Comment by skaapgif** [comment]
Yes. The real problem for me was the error message didn't help me identify and resolve the problem.

Your suggested error message would have made it very obvious why the parser is failing and how I can proceed.

**Comment by octogonz** [comment]
@skaapgif Here's a PR that clarifies this message and some other messages that had the same problem: https://github.com/Microsoft/tsdoc/pull/158
