### ISSUE TITLE
Line break is missing after tsdoc parsing

### ISSUE THREAD

**Issue by adventure-yunfei** [microsoft/tsdoc#181]
With following comment input:

```javascript
  /**
   * Returns the average of two numbers.
   * A new line.
   *
   * Another new line with extra line-break.
   */
```

Calling tsdoc parser:

```javascript
context = new TSDocParser().parseString(input);
console.log(context.docComment.emitAsTsdoc());
```

It returns following:
```javascript
/**
 * Returns the average of two numbers. A new line.
 *
 * Another new line with extra line-break.
 */
```

The line break before "A new line" is missing.

tsdoc version: 0.12.12.

From https://github.com/microsoft/tsdoc/pull/25 I thought it would keep the line-break.
Is this intended or a bug?

**Comment by adventure-yunfei** [comment]
After more investigation, the parsed docComment node actually contains the line break ("SoftBreak"), but result of `emitAsTsdoc()` doesn't.

The problem is that `@microsoft/api-extractor` package generates api json file without line-break. And I wonder this is the cause.

**Comment by adventure-yunfei** [comment]
From the demo https://github.com/microsoft/tsdoc/blob/746a8fb8fe89790107325c79e9077cdc8c83546a/playground/src/samples/advancedSample.ts#L2 I guess it's intended.

It's fine for me to make a workaround by using a html tag `<br />`. Closing this issue.

**Comment by octogonz** [comment]
@adventure-yunfei Some clarifications:

- We do want for `context.docComment.emitAsTsdoc()` to have an option where it renders `SoftBreak` and more-or-less reproduces the input string.  The only reason I didn't implement it is that I didn't need it right away.  For example I'd like API Extractor's .d.ts rollups to normalize the TSDoc comments, and this future option is how we would implement that.  Feel free to open a GitHub issue if you want this feature. 

- By design, `DocSoftBreak` is NOT meant to affect the rendered documentation website.  It merely captures TSDoc code comment layout, similar to newlines in an HTML document.  Whereas `DocParagraph` /does/ change the rendered output, similar to adding `<p>` to an HTML document.

- Thus the `emitAsTsdoc()` output is semantically equivalent to the input string, similar to how you might reformat an HTML document without affecting its meaning.

**Comment by iyarsius** [comment]
@octogonz hey,

> Thus the emitAsTsdoc() output is semantically equivalent to the input string, similar to how you might reformat an HTML document without affecting its meaning.

I got a case where this affect the rendered result, in @example tag:

i want to add a comment line on my example but since softbreak is not supported my code line is considered as a comment:

example:

input
```ts
// single line comment here
const result = aFunction(param);
```

output
```ts
// single line comment here const result = aFunction(param);
```

i can try something like:
```ts
// single line comment here

const result = aFunction(param);
```

but it's not looking good.

i tried the <br> workaround but the <br> is visible in the IDE intellisense so not looking good too.

any advice to fix this ?

**Comment by octogonz** [comment]
> any advice to fix this ?

The `@example` is meant to be used with code blocks (` ``` `).  Newlines will be preserved inside the code block.

Example here: https://api-extractor.com/pages/tsdoc/tag_example/

BTW this is a closed issue.  For new questions, create a new GitHub issue.  You can also ask directly in our [#tsdoc](https://rushstack.zulipchat.com/#narrow/stream/266672-tsdoc) chatroom, and we also have a monthly [Rush Hour](https://rushstack.io/community/events/) community video call where people can ask questions in person.
