### ISSUE TITLE
Create Reference Website/Documentation.

### ISSUE THREAD

**Issue by jginsburgn** [microsoft/tsdoc#262]
End users of TSDoc should have, alongside the [TSDoc Playground](https://microsoft.github.io/tsdoc) an easy-to-access reference for the usage of keywords and examples. As of now, the specification must be learnt by reading through the code. This, however, is troublesome from the perspective of consumers who are not interested in writing the tooling but just using it. My proposal is to have an analogue to [the documentation site of JSDoc](https://jsdoc.app/) or the eldest pioneer: [Javadoc](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html).

**Comment by thefoodiecoder** [comment]
This is a must to increase adoption. Currently many developers stay away from it due to unavailability of a reference documentation.

**Comment by takeitforwardsolutions** [comment]
Any movement on this and or can some of us offer to assist with this ask. I wanna review adopting this, but as mentioned above, specs and or documentation is needed.

**Comment by sg495** [comment]
Same here: I currently use https://github.com/microsoft/tsdoc/blob/master/tsdoc/src/details/StandardTags.ts as a reference for tags, but that is definitely not the way to go for increased adoption. 
I am more than happy to create a draft of documentation page from that file: would a markdown file to link in README.md be suitable?

**Comment by jginsburgn** [comment]
@sg495 that is very kind of you! I think that would be a cornerstone. Later, if needed, a full website could be stemmed from there. What do you think?

**Comment by octogonz** [comment]
I think we should just stand up a proper website using the https://microsoft.github.io/tsdoc/ website, which currently hosts the playground. Then everything will be in nice markdown files that people can contribute to.

I had been delaying this because it would be really great to incorporate @rbuckton's parser updates before putting together a bunch of docs.  But my time has been spread really thin this fall, so I barely have time to keep up with PRs.

In any case it is an engineer's vice to procrastinate a useful thing we could do real fast, in favor of an awesome thing that might be a long wait. Better to move forward in small steps.

Lemme see what I can put together.

**Comment by jginsburgn** [comment]
@octagonz thanks!

**Comment by takeitforwardsolutions** [comment]
@octogonz Thank You

**Comment by octogonz** [comment]
You can follow my progress here:

https://microsoft.github.io/tsdoc-website/

**Comment by MartynasZilinskas** [comment]
@octogonz `base` tag is missing. All links are broken.

**Comment by octogonz** [comment]
Right, it is a work-in-progress. :-)

I'll update this thread when it's done.

**Comment by jginsburgn** [comment]
Dope! Looking good ;)

**Comment by octogonz** [comment]
Status update:  🥳 Microsoft registered a DNS name for us: https://tsdoc.org/

The basic template and search are working, so now I just need to move the content over.

**Comment by jginsburgn** [comment]
Wow you’re really fast. Please tell me if you can use my help.

**Comment by takeitforwardsolutions** [comment]
@octogonz; Awesome, super fast! Eco that, please let me know if you want to delegate any tasks. Be glad to help out.

Don

**Comment by octogonz** [comment]
Let me get the basic content sketched out, and then it would be super useful to have people review it for mistakes/wording, and point out areas that are unclear or incomplete. It is actually very difficult to find volunteers to carefully read a big pile of docs. And it's difficult for the author to edit their own writing because you get "snow blind" from reading it too many times heheh.

I'll follow up when it's ready. It's holidays right now in the US but we should be able to get this wrapped up pretty soon. Thanks!

**Comment by takeitforwardsolutions** [comment]
Thank you for all the efforts on this. Sounds like a plan, take care and happy Turkey Day; just got done cooking mine. :)

**Comment by octogonz** [comment]
Progress update: I've posted an initial writeup of the tag definitions. I'll see if I can add some more specs over the weekend.

**Comment by octogonz** [comment]
Progress update: I've published an initial writeup of the TSDoc tag definitions. I'll see if I can add some more specs over the weekend.

https://tsdoc.org/

**Comment by octogonz** [comment]
This PR integrates the TSDoc Playground: https://github.com/microsoft/tsdoc/pull/269

**Comment by octogonz** [comment]
**Update:** I've completed an initial draft of the website content.  PR https://github.com/microsoft/tsdoc/pull/270 updates all the packages and README's to point to the new website.

This initial draft provides docs for every `@` tag. But we don't yet have docs for the grammar or other mechanics issues.  I'll aim to fill that out over the next few weeks as I find the time.

If anyone wants to help out by proofreading the pages and sharing questions/corrections/additions, that would be great!  Please create your issues/PRs in the new repo: https://github.com/microsoft/tsdoc.org-website

BTW we've also created a [#tsdoc](https://rushstack.zulipchat.com/#narrow/stream/266672-tsdoc) channel in the Rush Stack chatroom, in case people want to discuss TSDoc more interactively.  Might be fun!

Thanks everyone for inspiring me to get this done. 😋
