### ISSUE TITLE
api-doc install fails

### ISSUE THREAD

**Issue by HunterKohler** [microsoft/tsdoc#292]
After cloning the repository I ran the npm install as stated in the [readme](../tree/master/api-demo/README.md) (inside the [api-demo folder](../tree/master/api-demo)). 
```shell
$ npm install --no-package-lock
```
**The install did not work, see pastebins at the bottom.**

I suspect that this has something to do with versioning of either Node.js or g++. I am currently running the following:

```
 g++-10:  gcc version 10.2.0 (Homebrew GCC 10.2.0_4)
 node: v16.0.0
 npm: 7.11.0
 OS: macOS 11.2.3 20D91 x86_64
 Host: MacBookPro15,4
 Kernel: 20.3.0
 Shell: zsh 5.8
```

I don't really _need_ help with this. Just wanted to let y'all know.

## Pastebins
- [console output](https://pastebin.com/aQZqq9RN)
- [log file](https://pastebin.com/PhJL258M)

**Comment by octogonz** [comment]
@hunterkohler thanks for reporting this!

The problem is that you are using an unstable release of Node.js:

https://nodejs.org/en/about/releases/

The `node-sass` dependency does not publish prebuilt native binaries for unstable Node.js releases.  As a result, the `npm install` command falls back to invoking the C++ compiler, which failed due to a misconfiguration or incompatibility on your system.

The current LTS version is Node.js v14.  I confirmed that the demo builds without problems using that release.  We can update the docs to clarify this.

**Comment by tgmarinho** [comment]
Facing issue:

```
~/Developer/tsdoc/api-demo (main) » npm run build                                                                                                                                                      1 ↵ tgmarinho@Thiagos-MacBook-Pro

> api-demo@0.0.0 build
> heft test --clean

Using local Heft from /Users/tgmarinho/Developer/tsdoc/api-demo/node_modules/@rushstack/heft

/Users/tgmarinho/Developer/tsdoc/api-demo/node_modules/node-sass/lib/binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: Node Sass does not yet support your current environment: OS X Unsupported architecture (arm64) with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
```



node v16.18.0 LTS

**Comment by ecoms-ye** [comment]
the latest Node.js LTS is v18 now, and same problem when building `node-sass` with `node-gyp`

(succeed with node v14)
