### ISSUE TITLE
Any advice on generating .md files?

### ISSUE THREAD

**Issue by finom** [microsoft/tsdoc#305]
Thank you for your work! I'm a newbie at TSDoc and I thought there should be a tool that generates .md files. I'm working on an API that is going to be documented as a README file. I have already documented something but now I'm stuck figuring out how to generate human-readable files. It appeared not that easy and I suppose I need to implement a custom script for that using the parser. I hope no 😬. Can you please direct me to an NPM package or something like that that can help me to generate documentation? Thank you!

**Comment by Gerrit0** [comment]
There's a couple options. The one that matches TSDoc most closely is definitely https://api-extractor.com/pages/overview/demo_docs/, but API Extractor does a whole lot more than just documentation. Another alternative is TypeDoc with https://www.npmjs.com/package/typedoc-plugin-markdown to make it produce markdown instead of HTML.

**Comment by finom** [comment]
Thank you!
