### ISSUE TITLE
Pain around building with different versions of NPM.

### ISSUE THREAD

**Issue by iclanton** [Microsoft/tsdoc#88]
I've started to notice that this repo is fairly painful to build if there are inconsistencies between versions of NPM in build environments. For example, the Travis build uses NPM 5.6.0, but my dev box had NPM 6.4.1 and another CI box I'm using has NPM 3.10.8. The issues I've been fighting with are incompatibilities between package-lock files generated by different versions of NPM, and the lack of support for [path-based references](https://github.com/Microsoft/tsdoc/blob/master/api-demo/package.json#L8) in package.json files.

Additionally, because this repo now contains three projects, to build everything we have to install some dependencies multiple times.

What are people's thoughts about converting this repo to use a monorepo manager (ideally one that controls the version of the package manager) like Rush? That would eliminate a lot of the inconsistencies between build environments, simplify build, and speed up install times.

**Comment by iclanton** [comment]
I don't use vanilla NPM very often anymore, but I've also noticed that the package-lock files seem to change every time I run an install. Is that normal?

**Comment by pgonzal** [comment]
Something similar was brought up in [PR #62](https://github.com/Microsoft/tsdoc/pull/62), which ended up getting abandoned because the **package-lock.json** was not portable between different versions of NPM, and we don't have a simple way to lock down the version of NPM invoked by various developers/bots.

> I don't use vanilla NPM very often anymore, but I've also noticed that the package-lock files seem to change every time I run an install. Is that normal?

Yeah, I have that problem too.  I just revert the diff before committing to Git (unless I actually intended to update the lockfile).

**Comment by pgonzal** [comment]
Fixed by #89

**Comment by DanielRuf** [comment]
Not sure what Rush does but Yarn supports workspaces / monorepos out of the box and the engines field in package.json can lock the Yarn version.

**Comment by DanielRuf** [comment]
Seems to be very similar like pnpm.
